version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: irinamann/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/var/html/backend_static/
      - media:/app/media/

  frontend:
    image: irinamann/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.23.3-alpine
    ports:
      - "8000:80"
    volumes:
      - /infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - /frontend/build:/usr/share/nginx/html/
      - /docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend
