version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    container_name: postgre_db_foodgram
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-backend
    image: irinamann/foodgram_backend
    env_file: ../.env
    depends_on:
      - db
    volumes:
      - static:/backend_static/
      - media:/app/media/

  frontend:
    container_name: foodgram-front
    image: irinamann/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.23.3-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/backend_static/
      - media:/var/html/media/
    depends_on:
      - backend
