# Generated by Django 4.2.11 on 2024-05-06 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_link_alter_recipeingredients_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='short_url',
            new_name='short_link',
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_in_recipe', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
