# Generated by Django 4.2.11 on 2024-05-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_short_url_link_short_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AlterField(
            model_name='link',
            name='original_url',
            field=models.URLField(verbose_name='Полная ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.CharField(max_length=50, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
